### ISSUE TITLE
Question: Is easy discover of devices still possible?

### ISSUE THREAD

**Issue by sschuberth** [nightowlengineer/sonos-api-java#10]
Sorry for this question type of issue, but I'm currently looking at which Java library to use for a Sonos project I'm planning. Compared to [this (a bit dated) library](https://github.com/KilianB/Java-Sonos-Controller), whose [basic usage](https://github.com/KilianB/Java-Sonos-Controller#basic-usage) is to simply run `List<SonosDevice> devices = SonosDiscovery.discover();`, the [prerequisites for this library](https://github.com/nightowlengineer/sonos-api-java#prerequisites) seem rather complex. Is this due to Sonos having changed something on their side (and that dated library would not work anymore), or is it due to this library doing something different than the other library, or is it due to something else?

Thanks for any insights!

**Comment by nightowlengineer** [comment]
Apologies for the delayed (!) reply here. The API integration here is a different method to the more 'local' control offered through other methods. My reading of the documentation is that they hope to make the two consistent over the long term, but who knows when that will happen. This type of integration is more suited for web apps and similar where you want to offer some unique features on top of Sonos control, versus the more local control which is usually focused around providing a 'better' level of control for devices (in my opinion).

That said, the prereqs aren't overly onerous, but OAuth is certainly a lot more complex than 'just' discovering local network devices for sure.
